// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA-kFZkfi7PbaFvCBPg8Ysx92iQSEF2lps',
    appId: '1:732561561947:web:92adcf90ec548eee91227e',
    messagingSenderId: '732561561947',
    projectId: 'whatsapp-chat-app-c181a',
    authDomain: 'whatsapp-chat-app-c181a.firebaseapp.com',
    storageBucket: 'whatsapp-chat-app-c181a.firebasestorage.app',
    measurementId: 'G-4GQE2VWQ3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwfQRKK4dAZy4sj5O55Y6a_aRdb0JujXc',
    appId: '1:732561561947:android:9720f66e07702ba791227e',
    messagingSenderId: '732561561947',
    projectId: 'whatsapp-chat-app-c181a',
    storageBucket: 'whatsapp-chat-app-c181a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVoTo9If-SBYUWSzqYr0CtfG-SMMGRkpw',
    appId: '1:732561561947:ios:e0acbcf1ea99efff91227e',
    messagingSenderId: '732561561947',
    projectId: 'whatsapp-chat-app-c181a',
    storageBucket: 'whatsapp-chat-app-c181a.firebasestorage.app',
    iosBundleId: 'com.example.whatsappChatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVoTo9If-SBYUWSzqYr0CtfG-SMMGRkpw',
    appId: '1:732561561947:ios:e0acbcf1ea99efff91227e',
    messagingSenderId: '732561561947',
    projectId: 'whatsapp-chat-app-c181a',
    storageBucket: 'whatsapp-chat-app-c181a.firebasestorage.app',
    iosBundleId: 'com.example.whatsappChatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA-kFZkfi7PbaFvCBPg8Ysx92iQSEF2lps',
    appId: '1:732561561947:web:c22bf43db69dfab391227e',
    messagingSenderId: '732561561947',
    projectId: 'whatsapp-chat-app-c181a',
    authDomain: 'whatsapp-chat-app-c181a.firebaseapp.com',
    storageBucket: 'whatsapp-chat-app-c181a.firebasestorage.app',
    measurementId: 'G-5EWMLR6ZGY',
  );
}
